import type { ApiDateString } from './common';

export type CalendarEventType =
  | 'VENCIMIENTO_LOTE'
  | 'PAGO_PROXIMO'
  | 'APLICACION'
  | 'COMPRA_PROGRAMADA'
  | 'STOCK_BAJO'
  | 'CIERRE_CAMPANA';

export type CalendarEventStatus = 'PENDIENTE' | 'COMPLETADO' | 'CANCELADO';

export interface CalendarEvent {
  id: string;
  campaignId: string | null;
  ownerUserId: string | null;
  type: CalendarEventType;
  status: CalendarEventStatus;
  title: string;
  description: string | null;
  eventDate: ApiDateString;
  sourceEntity: string | null;
  sourceEntityId: string | null;
  isAutoGenerated: boolean;
  metadata: Record<string, string | number | boolean | null> | null;
  createdAt: ApiDateString;
  updatedAt: ApiDateString;
}

export interface ListCalendarEventsQuery {
  campaignId?: string;
  ownerUserId?: string;
  type?: CalendarEventType;
  status?: CalendarEventStatus;
  from?: string;
  to?: string;
}
