import { NotFoundException } from '@nestjs/common';
import { CalendarEventStatus, CalendarEventType, Prisma, UserRole } from '@prisma/client';
import { CalendarEventsUseCase } from './calendar-events.use-case';

describe('CalendarEventsUseCase', () => {
  const tenantId = 'tenant-1';
  const userId = 'user-1';
  const eventId = 'event-1';

  function event(overrides: Record<string, unknown> = {}) {
    return {
      id: eventId,
      tenantId,
      campaignId: 'campaign-1',
      ownerUserId: userId,
      type: CalendarEventType.PAGO_PROXIMO,
      status: CalendarEventStatus.PENDIENTE,
      title: 'Pago pendiente',
      description: null,
      eventDate: new Date('2026-06-01T00:00:00.000Z'),
      sourceEntity: 'PayableAccount',
      sourceEntityId: 'payable-1',
      isAutoGenerated: true,
      metadata: null,
      createdAt: new Date('2026-05-01T00:00:00.000Z'),
      updatedAt: new Date('2026-05-01T00:00:00.000Z'),
      ...overrides,
    };
  }

  function createUseCase(prismaOverrides: Record<string, unknown>) {
    const prisma = {
      inventoryLot: { findMany: jest.fn().mockResolvedValue([]) },
      agriculturalCampaign: { findMany: jest.fn().mockResolvedValue([]) },
      calendarEvent: {
        findMany: jest.fn().mockResolvedValue([]),
        findFirst: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
      },
      ...prismaOverrides,
    };

    return {
      prisma,
      useCase: new CalendarEventsUseCase(prisma as never),
    };
  }

  it('lists only own and global events for agriculturists', async () => {
    const visibleEvent = event();
    const { prisma, useCase } = createUseCase({
      calendarEvent: {
        findMany: jest.fn().mockResolvedValue([visibleEvent]),
        findFirst: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
      },
    });

    await expect(
      useCase.list(tenantId, { userId, role: UserRole.AGRICULTOR }, {}),
    ).resolves.toEqual([expect.objectContaining({ id: eventId, ownerUserId: userId })]);

    expect(prisma.calendarEvent.findMany).toHaveBeenCalledWith({
      where: {
        tenantId,
        OR: [{ ownerUserId: userId }, { ownerUserId: null }],
      },
      orderBy: [{ eventDate: 'asc' }, { createdAt: 'desc' }],
      take: 300,
    });
  });

  it('lets directiva list global events with owner filter', async () => {
    const { prisma, useCase } = createUseCase({
      calendarEvent: {
        findMany: jest.fn().mockResolvedValue([event()]),
        findFirst: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
      },
    });

    await useCase.list(tenantId, { userId: 'directiva-1', role: UserRole.DIRECTIVA }, { ownerUserId: userId });

    expect(prisma.calendarEvent.findMany).toHaveBeenCalledWith({
      where: { tenantId, ownerUserId: userId },
      orderBy: [{ eventDate: 'asc' }, { createdAt: 'desc' }],
      take: 300,
    });
  });

  it('creates missing lot expiration event once using source entity', async () => {
    const lot = {
      id: 'lot-1',
      tenantId,
      campaignId: 'campaign-1',
      ownerUserId: userId,
      productId: 'product-1',
      lotNumber: 'LOTE-1',
      expirationDate: new Date('2026-08-01T00:00:00.000Z'),
      currentQuantity: new Prisma.Decimal(3),
      product: {
        id: 'product-1',
        name: 'Glifosato',
        unit: 'L',
        minimumStock: new Prisma.Decimal(1),
      },
    };
    const { prisma, useCase } = createUseCase({
      inventoryLot: { findMany: jest.fn().mockResolvedValue([lot]) },
      calendarEvent: {
        findMany: jest.fn().mockResolvedValue([]),
        findFirst: jest.fn().mockResolvedValue(null),
        create: jest.fn(),
        update: jest.fn(),
      },
    });

    await useCase.list(tenantId, { userId, role: UserRole.AGRICULTOR }, { type: CalendarEventType.VENCIMIENTO_LOTE });

    expect(prisma.calendarEvent.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        tenantId,
        campaignId: 'campaign-1',
        ownerUserId: userId,
        type: CalendarEventType.VENCIMIENTO_LOTE,
        sourceEntity: 'InventoryLot',
        sourceEntityId: 'lot-1',
      }),
    });
  });

  it('updates existing automatic event instead of duplicating it', async () => {
    const lot = {
      id: 'lot-1',
      tenantId,
      campaignId: 'campaign-1',
      ownerUserId: userId,
      productId: 'product-1',
      lotNumber: 'LOTE-1',
      expirationDate: new Date('2026-08-01T00:00:00.000Z'),
      currentQuantity: new Prisma.Decimal(3),
      product: {
        id: 'product-1',
        name: 'Glifosato',
        unit: 'L',
        minimumStock: new Prisma.Decimal(1),
      },
    };
    const { prisma, useCase } = createUseCase({
      inventoryLot: { findMany: jest.fn().mockResolvedValue([lot]) },
      calendarEvent: {
        findMany: jest.fn().mockResolvedValue([]),
        findFirst: jest.fn().mockResolvedValue(event({ id: 'existing-event' })),
        create: jest.fn(),
        update: jest.fn(),
      },
    });

    await useCase.list(tenantId, { userId, role: UserRole.AGRICULTOR }, { type: CalendarEventType.VENCIMIENTO_LOTE });

    expect(prisma.calendarEvent.create).not.toHaveBeenCalled();
    expect(prisma.calendarEvent.update).toHaveBeenCalledWith({
      where: { id: 'existing-event' },
      data: expect.objectContaining({
        title: 'Vencimiento de Glifosato',
      }),
    });
  });

  it('marks a visible event as completed', async () => {
    const { prisma, useCase } = createUseCase({
      calendarEvent: {
        findMany: jest.fn(),
        findFirst: jest.fn().mockResolvedValue(event()),
        create: jest.fn(),
        update: jest.fn().mockResolvedValue(event({ status: CalendarEventStatus.COMPLETADO })),
      },
    });

    await expect(
      useCase.complete(tenantId, { userId, role: UserRole.AGRICULTOR }, eventId),
    ).resolves.toEqual(expect.objectContaining({ status: CalendarEventStatus.COMPLETADO }));

    expect(prisma.calendarEvent.update).toHaveBeenCalledWith({
      where: { id: eventId },
      data: { status: CalendarEventStatus.COMPLETADO },
    });
  });

  it('rejects completing an invisible event', async () => {
    const { useCase } = createUseCase({
      calendarEvent: {
        findMany: jest.fn(),
        findFirst: jest.fn().mockResolvedValue(null),
        create: jest.fn(),
        update: jest.fn(),
      },
    });

    await expect(
      useCase.complete(tenantId, { userId, role: UserRole.AGRICULTOR }, eventId),
    ).rejects.toBeInstanceOf(NotFoundException);
  });
});
